# Generated by Django 4.0.5 on 2022-09-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django3App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlotRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.CharField(max_length=50)),
                ('roommates', models.CharField(max_length=150)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alotroom', to='Django3App.student')),
            ],
        ),
    ]
