# Generated by Django 4.0.5 on 2022-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django3App', '0002_regparent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegParent',
            new_name='RegParentModel',
        ),
    ]
